import React from "react";
import Head from "next/head";
import HeadersInfo from "../Components/HeadersInfo";
import Headers from "../Components/Headers";
import Footers from "../Components/Footers";
import HomeCareer from "../Components/HomeCareer";

export default function career() {
  return (
    <>
      <Head>
        <title>CAREER | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />

      <HomeCareer />
      <Footers />
    </>
  );
}
