import React from "react";
import HeadersInfo from "../Components/HeadersInfo";
import Head from "next/head";
import Headers from "../Components/Headers";
import Footers from "../Components/Footers";
import HomeDirector from "../Components/HomeDirector";

export default function director() {
  return (
    <>
      <Head>
        <title>DIRECTOR | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />
      <HomeDirector />

      <Footers />
    </>
  );
}
