import React from "react";
import Head from "next/head";
import HeadersInfo from "../Components/HeadersInfo";
import Headers from "../Components/Headers";
import Footers from "../Components/Footers";
import HomeInfo from "../Components/HomeInfo";

export default function information() {
  return (
    <>
      <Head>
        <title>INFORMATIONS | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />

      <HomeInfo />
      <Footers />
    </>
  );
}
