import Head from "next/head";
import React from "react";
import HeadersInfo from "../Components/HeadersInfo";
import Footers from "../Components/Footers";
import Headers from "../Components/Headers";
import HomeMajors from "../Components/HomeMajors";

export default function majors() {
  return (
    <>
      <Head>
        <title>MAJORS | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />

      <HomeMajors />
      <Footers />
    </>
  );
}
