import Head from "next/head";
import HeadersInfo from "../Components/HeadersInfo";
import Headers from "../Components/Headers";
import Footers from "../Components/Footers";
import HomePmb from "../Components/HomePmb";
import { removeTokenStateClass } from "../src/ActionTypes";
export default function pmb() {
  removeTokenStateClass();
  return (
    <>
      <Head>
        <title>PMB | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />
      <HomePmb />
      <Footers />
    </>
  );
}
