import React from "react";
import Head from "next/head";
import HeadersInfo from "../Components/HeadersInfo";
import Footers from "../Components/Footers";
import Headers from "../Components/Headers";
import HeroProfile from "../Components/HeroProfile";
import HomeProfile from "../Components/HomeProfile";

export default function profile() {
  return (
    <>
      <Head>
        <title>PROFILE | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />
      <HeroProfile />
      <HomeProfile />
      <Footers />
    </>
  );
}
