import Head from "next/head";
import HeadersInfo from "../Components/HeadersInfo";
import Headers from "../Components/Headers";
import Footers from "../Components/Footers";
import HomeRegister from "../Components/HomeRegister";

import { AuthStateRegister } from "../src/ActionTypes";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function register() {
  const rou = useRouter();

  const [state, setstate] = useState(false);
  useEffect(() => {
    const StateClass = AuthStateRegister();
    if (!StateClass) {
      rou.push("/pmb");
    }
    setstate(StateClass);
  }, [state]);

  return (
    <>
      <Head>
        <title>REGISTRATION | POLITEKNIK PGRI BANTEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadersInfo />
      <Headers />
      <HomeRegister />
      <Footers />
    </>
  );
}
